name: dynamic_polls
description: "A Customizable Polls for Flutter. Simple, easy to use and highly customizable."
version: 0.0.6
homepage: "https://github.com/SwanFlutter/dynamic_polls.git"

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  get_x_storage: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:


